[project]
name = "pyroomacoustics_interface"
version = "0.1.0"
description = "Python package for acoustics research."
requires-python = ">=3.11"
authors = [
    { name = 'The CHORAS developers' },
    { name = "Marco Berzborn", email = "m.berzborn@tue.nl" },
]
keywords = [
    "pyroomacoustics",
    "ray-tracing",
    "image-source method",
    "acoustic simulation",
    "geometrical acoustics",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy>=1.23.0",
    "gmsh",
    "pyroomacoustics>=0.8.0",
    "requests",
    "pyfar>=0.8.0",
    "pyrato>=1.0.0",
    "pandas",
]

[project.optional-dependencies]
deploy = [
    "twine",
    "wheel",
    "build",
    "setuptools",
    "bump-my-version",
]

tests = [
    "pytest",
    "pytest-cov",
    "watchdog",
    "ruff",
    "coverage",
]

docs = [
    "sphinx",
    "autodocsumm>=0.2.14",
    "pydata-sphinx-theme",
    "sphinx_mdinclude",
    "sphinx-design",
    "sphinx-favicon",
    "sphinx-reredirects",
]

dev = ["pyroomacoustics_interface[deploy,tests,docs]"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyroomacoustics_interface"]

[project.scripts]
pyroomacoustics_interface = "pyroomacoustics_interface:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 79
lint.ignore = [
    "D200",   # One-line docstring should fit on one line with quotes
    "D202",   # No blank lines allowed after function docstring
    "D205",   # 1 blank line required between summary line and description
    "D401",   # First line should be in imperative mood
    "D404",   # First word of the docstring should not be "This"
    "B006",   # Do not use mutable data structures for argument defaults
    "B008",   # Do not perform calls in argument defaults
    "PT018",  # Assertion should be broken down into multiple parts
    "PT019",  # Fixture `_` without value is injected as parameter

]
lint.select = [
    "B",      # bugbear extension
    "ARG",    # Remove unused function/method arguments
    "C4",     # Check for common security issues
    "E",      # PEP8 errors
    "F",      # Pyflakes
    "W",      # PEP8 warnings
    "D",      # Docstring guidelines
    "NPY",    # Check all numpy related deprecations
    "D417",   # Missing argument descriptions in the docstring
    "PT",     # Pytest style
    "A",      # Avoid builtin function and type shadowing
    "ERA",    # No commented out code
]

# Ignore missing docstrings in tests


[tool.ruff.lint.pydocstyle]
convention = "numpy"
