"""Module implementing a CHORAS interface for MoDART.
"""
import sys
import json
import gmsh
import numpy as np
from pathlib import Path

from raves import compute_ART, compute_MoDART, run_MoDART
from raves.src.utils import sanitize_ascii

from numpy.random import default_rng
from scipy.signal import butter, sosfilt
from scipy.interpolate import make_interp_spline

from .definition import SimulationMethod


def save_converted_mesh(geo_file_path: str | Path,
                        output_folder_path: str | Path) -> None:
    """
    Read a .geo file (using gmsh), triangulate its surfaces, and save the result
     in Wavefront format (.obj + .mtl) as expected by MoD-ART.

    Parameters
    ----------
    geo_file_path : str or Path
        Path to the .geo file to be read.
    output_folder_path : str or Path
        Path to the folder where converted mesh files will be saved.
    """
    if not Path(geo_file_path).is_file():
        raise FileNotFoundError('The specified .geo file could not be found.')
    if not Path(output_folder_path).is_dir():
        raise NotADirectoryError('The specified output folder could not be found.')

    # Run the gmsh session in a "protected" scope to make sure it gets finalized no matter what.
    gmsh.initialize()
    try:
        # This factor scales the size of triangles generated by gmsh.
        # The triangulation has no effect on the results, it only slows things down;
        #  make it as large as possible.
        gmsh.option.setNumber('Mesh.MeshSizeFactor', 100)

        # Read the input file...
        gmsh.open(geo_file_path)
        # ...and mesh its surfaces (2D elements).
        gmsh.model.mesh.generate(2)

        # Retrieve the integer IDs of all surface materials (2D physical groups).
        material_tags = gmsh.model.getPhysicalGroups(dim=2)
        # Retrieve the names of surface materials, as strings.
        material_names = [gmsh.model.getPhysicalName(dim, tag)
                          for (dim, tag) in material_tags]
        # Retrieve the lists of "entities" characterized by each of the retrieved surface materials.
        surface_entities = {name: [tag for dim, tag in gmsh.model.getEntitiesForPhysicalName(name)]
                            for name in material_names}
        
        # Retrieve the 3D coordinates of mesh vertices, and format them as an (N, 3) array.
        node_tags_all, coords_all, _ = gmsh.model.mesh.getNodes()
        vertices = coords_all.reshape((len(node_tags_all), 3))
        num_vertices = vertices.shape[0]

        # Reference object for gmsh elements of "triangle" type.
        gmsh_triangle_type = gmsh.model.mesh.getElementType('triangle', 1)

        # Prepare the lists which will form the Wavefront-formatted faces.
        triangles = list()
        triangle_materials = list()
        triangle_patch_ids = list()
        num_patches = 0

        # Cycle over the detected surface materials.
        for material_name, entity_tags_list in surface_entities.items():
            # For each surface material, we found a list of "entities" which may be
            #  different polygons made of that material.
            # TODO: Confirm if it actually works like that.
            for tag in entity_tags_list:
                # Find the triangles which form the surface entity.
                face_nodes = gmsh.model.mesh.getElementFaceNodes(gmsh_triangle_type, 3, tag=tag)
                num_triangles_in_element = len(face_nodes) // 3
                # Just in case a non-triangular surface element snuck in: ignore it.
                if num_triangles_in_element == 0:
                    continue
                # This forms an (M, 3) integer-valued array of vertex indices (1-indexed).
                faces = np.reshape(face_nodes, (num_triangles_in_element, 3))

                # For the purpose of MoD-ART, each "entity" is used as a surface patch.
                # TODO: Allow automatic segmentation with maximum area threshold (will use code from our upcoming paper).
                num_patches += 1
                for face in faces:
                    triangles.append(face)
                    # Note: the material name is "sanitized" to only latin letters, digits, and underscores.
                    triangle_materials.append(sanitize_ascii(material_name))
                    triangle_patch_ids.append(num_patches)
    finally:
        # Close the gmsh session even in case of an exception.
        gmsh.finalize()

    # Convert the lists to arrays, for easier handling.
    triangles = np.array(triangles)
    num_triangles = triangles.shape[0]
    triangle_patch_ids = np.array(triangle_patch_ids)

    # The surface normals are inverted w.r.t. what MoD-ART expects. Flip them (by inverting the triangle winding).
    # TODO: How can this be tested, to prevent breaking changes in the future? MoD-ART does not raise any errors if the normals are flipped.
    triangles = triangles[:, ::-1]

    # Make sure all vertex indices are valid.
    assert np.all(triangles <= num_vertices), 'The triangle definitions include vertex indices out of range.'

    # Prepare all of the lines to be written in each of the Wavefront files.
    obj_output_lines = list()
    mtl_output_lines = list()

    # The .obj always starts by specifying the .mtl.
    obj_output_lines.append('mtllib mesh.mtl\n')

    # List all of the vertex coordinates, in order, in the .obj.
    for v in vertices:
        line = 'v ' + ' '.join([str(c) for c in v]) + '\n'
        obj_output_lines.append(line)
    
    # List all of the triangles in the .obj, and add their materials to the .mtl.
    latest_patch_name = None
    for i in range(num_triangles):
        # Consider the "dummy" material name assigned to this triangle.
        patch_name = f'Patch_{triangle_patch_ids[i]}_Mat_{triangle_materials[i]}'
        # If it is different from the latest material specified in the .obj, it needs to be added.
        if patch_name != latest_patch_name:
            obj_output_lines.append(f'usemtl {patch_name}\n')

            # It also needs to be added to the .mtl, as it is a new material definition.
            mtl_output_lines.append(f'newmtl {patch_name}\n')
            # Assign the "dummy" material a random RGB color.
            r, g, b = np.round(np.random.uniform(size=3), 3)
            mtl_output_lines.append(f'Kd {r} {g} {b}\n')

            # All following triangles in the .obj implicitly use this material.
            latest_patch_name = patch_name

        # Add the vertex indices forming the triangle.
        # Note: these are already 1-indexed, as they should be for the Wavefront format.
        obj_output_lines.append('f ' + ' '.join([str(v) for v in triangles[i]]) + '\n')
    
    # Appending filenames using " / " requires this to be a Path object, not a plain string.
    if type(output_folder_path) == str:
        output_folder_path = Path(output_folder_path)
    
    with open(str(output_folder_path / 'mesh.obj'), mode='w') as file:
        for line in obj_output_lines:
            file.write(line)
    with open(str(output_folder_path / 'mesh.mtl'), mode='w') as file:
        for line in mtl_output_lines:
            file.write(line)


def save_materials_file(json_file_path: str | Path) -> None:
    """
    Read the JSON settings file and save surface material data in the .csv format
     expected by MoD-ART, in the folder spacified in the JSON.

    Parameters
    ----------
    json_file_path : str or Path
        Path to the JSON file to be read.
    """
    if not Path(json_file_path).is_file():
        raise FileNotFoundError('The specified JSON file could not be found.')

    # Load the input JSON file.
    with open(json_file_path, 'r') as json_file:
        result_container = json.load(json_file)
    
    # The formatted data needs to be saved in the specified folder.
    if 'MoDART_data_subfolder' not in result_container:
        raise ValueError('The MoD-ART data folder is not specified in the JSON.')
    output_folder_path = Path(result_container['MoDART_data_subfolder'])
    if not Path(output_folder_path).is_dir():
        raise NotADirectoryError('The MoD-ART data folder could not be found.')
    
    # TODO: For now, we assume that the length of each
    #           result_container['absorption_coefficients'].values()
    #       is the same as the length of each
    #           result_container['results'][res_idx]['frequencies']
    #       Eventually this will change. This portion of the code will need to be updated.
    freq_bands = None
    for res in result_container['results']:
        freqs = np.array(res['frequencies'], dtype=float)
        if freq_bands is None:
            freq_bands = freqs
        else:
            assert np.allclose(freq_bands, freqs)
    
    # Arrange the coefficients into a dict.
    absorptions = dict()
    for material, coeff_string in result_container['absorption_coefficients'].items():
        coeffs = np.array(coeff_string.replace(',', '').split(' '), dtype=float)
        if freq_bands is None:
            raise RuntimeError('The frequencies should be known before the coefficients are read.')
        else:
            assert len(freq_bands) == len(coeffs)
            # Note: the material name is "sanitized" to only latin letters, digits, and underscores,
            #       MATCHING THE NAME REPORTED IN THE CONVERTED MESH FILES.
            absorptions[sanitize_ascii(material)] = coeffs
    
    # Save the data in .csv format.
    with open(str(output_folder_path / 'materials.csv'), mode='w') as file:
        line = 'Frequencies, ' + ', '.join([str(f) for f in freq_bands]) + '\n'
        file.write(line)

        for material, coeffs in absorptions.items():
            line = material + ', ' + ', '.join([str(c) for c in coeffs]) + '\n'
            file.write(line)

            # TODO: For now, scattering coefficients are arbitrarily set to 0.3.
            #       Eventually the true values will be specified in the JSON.
            line = material + ', 0.3\n'
            file.write(line)


def noise_shaping(fs: int | float,
                  band_centers: np.ndarray,
                  envelopes: np.ndarray,
                  order: int = 5) -> np.ndarray:
    """
    Generate impulse responses based on band-wise signal envelopes, through the
     amplitude modulation of stochastic signals.

    Parameters
    ----------
    fs : int
        Audio sample rate of the envelopes AND the final response, in Hertz.
    band_centers : np.ndarray
        One-dimensional array containing the center frequency of each band, in Hertz.
    envelopes : np.ndarray
        Four-dimensional array containing the modulation envelopes.
        It has shape (S, R, B, T), where:
        - S is the number of sound sources
        - R is the number of receivers
        - B is the number of frequency bands (must match length of "band_centers")
        - T is the duration in samples.
    order : int
        Order passed to the "butter" bandpass filtering function.
        Flat responses are achieved with odd numbers greater than three.
    
    Returns
    -------
    response : np.ndarray
        Three-dimensional array containing the room impulse responses.
        It has shape (S, R, T), matching the energy envelopes (all bands are combined).
    
    Notes
    -----
    The provided envelopes are assumed to be AMPLITUDE, i.e., square-rooted energy.
    The stochastic signal used for modulation is a Poisson process with lambda=0.5.
    The signal is generated only once and used for all sources, receivers, and
     frequency bands (band-passed appropriately for each).
    The band-passing occurs BEFORE the amplitude modulation, so out-of-band artefacts
     may be introduced if the envelopes are very jagged.
    """
    assert band_centers.ndim == 1
    assert envelopes.ndim == 4
    assert envelopes.shape[2] == band_centers.shape[0]

    num_bands = band_centers.shape[0]
    duration_in_samples = envelopes.shape[3]

    # Random number generator for the stochastic signal to be modulated.
    rng = default_rng()
    
    # White noise
    #   noise_signal = rng.normal(size=duration_in_samples)
    # Poisson process
    noise_signal = rng.poisson(lam=0.05, size=duration_in_samples).astype(float)

    # Ensure the noise signal has unit energy per second, matching the
    #   convention used to generate the echograms.
    noise_signal *= np.sqrt(duration_in_samples * fs / np.sum(noise_signal**2))
    
    # Factor for octave-band boundaries.
    # TODO: These may become third-octave bands at some point.
    band_bound = np.sqrt(2)

    # Consider the frequency band centers provided alongside the input data.
    # Ensure that all frequencies support filtering with the given sample rate.
    if np.any(band_centers * band_bound >= fs):
        print('Warning: the audio sample rate is too low for some frequency bands.')
        # Select only the acceptable bands.
        band_centers = band_centers[band_centers * band_bound < fs]
        # Update the number of rendered bands.
        num_bands = len(band_centers)
        # Drop unused bands from the echogram, to preserve the right shape.
        envelopes = envelopes[:, :, :num_bands]
    
    # Prepare an array for the band-pass filtered signals.
    filtered_noise_signals = np.zeros((num_bands, duration_in_samples))
    
    for b in range(num_bands):
        # Prepare the suitable band-pass filter...
        sos = butter(order, (band_centers[b] / band_bound,
                             band_centers[b] * band_bound),
                     btype='bandpass', output='sos', fs=fs)
        # ...and apply it to the stochastic signal.
        filtered_noise_signals[b] = sosfilt(sos, noise_signal)
    
    # The envelope array has shape (S, R, B, T), the noise signals have shape (B, T):
    #   we need to add two "leading" dimensions, which is done using [None, None].
    modulated_noise_signals = envelopes * filtered_noise_signals[None, None]
    
    # The dimension of index 2 holds the separate frequency bands.
    # Sum the array along that dimension to obtain the complete impulse responses.
    return np.sum(modulated_noise_signals, axis=2)


def schroeder_curves(fs: int | float,
                     band_centers: np.ndarray,
                     echograms: np.ndarray) -> np.ndarray:
    """
    Convert a set of echograms into backward-integrated energy curves, with bandwitdh correction.

    Parameters
    ----------
    fs : int
        Audio sample rate used for the bandwidth correction, in Hertz.
    band_centers : np.ndarray
        One-dimensional array containing the center frequency of each band, in Hertz.
    echograms : np.ndarray
        Four-dimensional array containing the energy envelopes.
        It has shape (S, R, B, T), where:
        - S is the number of sound sources
        - R is the number of receivers
        - B is the number of frequency bands (must match length of "band_centers")
        - T is the duration in samples.
    
    Returns
    -------
    response : np.ndarray
        Array of the same shape as "echograms", containing the energy decay curves.
    """
    assert band_centers.ndim == 1
    assert echograms.ndim == 4
    assert echograms.shape[2] == band_centers.shape[0]

    # Factor for octave-band boundaries.
    # TODO: These may become third-octave bands at some point.
    band_bound = np.sqrt(2)
    lower_thres = band_centers / band_bound
    upper_thres = band_centers * band_bound
    band_widths = upper_thres - lower_thres

    nyquist = fs / 2
    echograms *= band_widths[None, None, :, None] / nyquist

    return np.cumsum(echograms[:, :, :, ::-1], axis=-1)[:, :, :, ::-1]


class MoDARTMethod(SimulationMethod):
    """Interface class to run the MoDART method.

    The class implements a method to run the calculations for the
     MoD-ART analysis and generate responses using its parameters.
    All required configuration parameters are expected to be provided
     in the input JSON file passed during initialization.
    """
    # TODO: Add more "failure" tests: make sure the correct exception is raised, e.g.,
    #           "with pytest.raises(FileNotFoundError, match='part of error message'):"
    # TODO: Fill out metrics like T30? It will be done by the backend eventually.

    def __init__(self, input_json_path: str | Path):
        """Initialize the MoD-ART interface for the given JSON file.

        Parameters
        ----------
        json_file_path : str | Path
            Path to the JSON configuration file.
        """
        super().__init__(input_json_path)

    def run_simulation(self) -> None:
        """Prepare the input data and run the method proper.
        """
        # Load the JSON configuration file.
        with open(self.input_json_path, 'r') as json_file:
            result_container = json.load(json_file)

        # Create a folder for the "temporary" ART and MoD-ART data.
        geo_path = Path(result_container['geo_path'])
        temp_subfolder = geo_path.parent / (str(geo_path.stem) + '_MoDART_data')
        result_container['MoDART_data_subfolder'] = str(temp_subfolder)
        if not temp_subfolder.is_dir():
            Path.mkdir(temp_subfolder)
        
        # Save the updated JSON (with the added MoDART_data_subfolder field).
        with open(self.input_json_path, 'w') as json_output:
            json_output.write(json.dumps(result_container, indent=4))

        # Convert the .geo file into the format expected by MoD-ART.
        try:
            save_converted_mesh(result_container['geo_path'], temp_subfolder)
        except Exception as exc:
            raise RuntimeError('Failed to reformat the input mesh as required.') from exc

        # Save the material information into the .csv file expected by MoD-ART.
        try:
            save_materials_file(self.input_json_path)
        except Exception as exc:
            raise RuntimeError('Failed to reformat the material properties as required.') from exc

        # Run a one-shot MoD-ART simulation.
        try:
            self._modart_method()
        except Exception as exc:
            raise RuntimeError('Failed to run the MoD-ART method.') from exc

    def _modart_method(self) -> None:
        """
        Run a one-shot MoD-ART simulation, comprising:
        - preparation of ART model (surface integrals);
        - analysis of ART model (modal decomposition);
        - generation of energy envelopes from MoD-ART parameters;
        - generation of impulse responses from energy envelopes.
        """
        # Load the JSON file and extract its relevant contents.
        with open(self.input_json_path, 'r') as json_file:
            result_container = json.load(json_file)

        environment_folder = result_container['MoDART_data_subfolder']
        response_duration = result_container['simulationSettings']['durat']
        echogram_sample_rate = result_container['simulationSettings']['f_e']
        audio_sample_rate = result_container['simulationSettings']['sampling_rate']
        multiprocess_pool_size = result_container['simulationSettings']['pool']
        humidity = result_container['simulationSettings']['humi']
        temperature = result_container['simulationSettings']['temp']
        pressure = result_container['simulationSettings']['pres']
        points_per_square_meter = result_container['simulationSettings']['ppsm']
        rays_per_hemisphere = result_container['simulationSettings']['rays']
        T60_threshold = result_container['simulationSettings']['T60']
        max_slopes_per_band = result_container['simulationSettings']['slopes']

        # Each element of "results" is a simulation request for a different source in the same environment,
        #  which is analyzed only once. All share the same settings and the same list of receivers.
        num_srcs = len(result_container['results'])
        if num_srcs == 0:
            raise ValueError('No source positions specified.')
        
        source_positions = np.zeros((num_srcs, 3))
        for src_idx in range(num_srcs):
            src_dict = result_container['results'][src_idx]
            
            source_positions[src_idx] = np.array([src_dict['sourceX'],
                                                  src_dict['sourceY'],
                                                  src_dict['sourceZ']])
            
            these_receiver_positions = np.array([[pos['x'], pos['y'], pos['z']]
                                                 for pos in src_dict['responses']])
            
            if src_idx == 0:
                receiver_positions = these_receiver_positions
            elif these_receiver_positions.shape != receiver_positions.shape:
                raise ValueError('The list of receiver positions is not the same for all sources.')
            elif not np.allclose(receiver_positions, these_receiver_positions):
                raise ValueError('The list of receiver positions is not the same for all sources.')

        num_rcvs = receiver_positions.shape[0]
        if num_rcvs == 0:
            raise ValueError('No receiver positions specified.')
        
        # Run the pre-processing (shared by all sources, receivers).
        # Step 1: Prepare the ART model.
        try:
            compute_ART(folder_path=environment_folder,
                        multiprocess_pool_size=multiprocess_pool_size,
                        humidity=humidity, temperature=temperature, pressure=pressure,
                        points_per_square_meter=points_per_square_meter,
                        rays_per_hemisphere=rays_per_hemisphere)
        except Exception as exc:
            raise RuntimeError('Failed to create the ART model (environment pre-processing).') from exc
        
        # Claim that the ART model constitutes 40% of the overall progress (very arbitrary).
        for src_idx in range(num_srcs):
            result_container['results'][src_idx]['percentage'] = 40
        # Save the updated JSON.
        with open(self.input_json_path, 'w') as json_output:
            json_output.write(json.dumps(result_container, indent=4))

        # Step 2: Analyze the ART model.
        try:
            compute_MoDART(folder_path=environment_folder,
                            echogram_sample_rate=echogram_sample_rate,
                            T60_threshold=T60_threshold,
                            max_slopes_per_band=max_slopes_per_band,
                            skip_T60_plots=True,
                            raise_on_failure=True)
        except Exception as exc:
            raise RuntimeError('Failed to run the modal analysis (environment pre-processing).') from exc

        # Claim that the MoD-ART analysis constitutes another 40% of the overall progress (very arbitrary).
        for src_idx in range(num_srcs):
            result_container['results'][src_idx]['percentage'] = 80
        # Save the updated JSON.
        with open(self.input_json_path, 'w') as json_output:
            json_output.write(json.dumps(result_container, indent=4))

        # Generate the echograms with MoD-ART.
        try:
            MoDART_tuple = run_MoDART(environment_folder,
                                      source_positions, receiver_positions,
                                      echogram_duration=response_duration,
                                      echogram_sample_rate=echogram_sample_rate,
                                      humidity=humidity, temperature=temperature, pressure=pressure,
                                      num_rays=rays_per_hemisphere)
            MoDART_echograms, frequencies, MoDART_data = MoDART_tuple
        except Exception as exc:
            raise RuntimeError(f'Failed to generate echograms for simulation #{src_idx+1}.') from exc

        # Some MoD-ART parameters will be saved in the JSON.
        # For now, this is just for debugging/testing.
        result_container['MoDART_data'] = {
            'T60': MoDART_data['T60'].tolist(),
            'Band idx': MoDART_data['Band idx'].tolist(),
            'Eigenvector shape': MoDART_data['V_hat'].shape
        }

        for src_idx in range(num_srcs):
            # Noise-shaping code. TODO: may need revising.
            # Claim that the response generation constitutes the last 5% of the overall progress (very arbitrary).
            result_container['results'][src_idx]['percentage'] = 95
            # Save the updated JSON.
            with open(self.input_json_path, 'w') as json_output:
                json_output.write(json.dumps(result_container, indent=4))
            
            # Prepare the audio-rate time intervals at which we'll evaluate the upsampled echogram.
            echogram_time_axis = np.arange(0, response_duration, 1 / echogram_sample_rate)
            audio_time_axis = np.arange(0, response_duration, 1 / audio_sample_rate)

            # We use a linear interpolation, because any other upsampling algorithm risks introducing negative values.
            linear_spline = make_interp_spline(echogram_time_axis, MoDART_echograms, k=1, axis=-1)
            upsampled_echograms = linear_spline(audio_time_axis)
            
            # Normalize w.r.t. the new sample rate, to preserve the energy-per-second definition of echogram values.
            upsampled_echograms *= echogram_sample_rate / audio_sample_rate
                    
            # Translate the energy envelopes to amplitude envelopes.
            envelopes = np.sqrt(upsampled_echograms)

            # Amplitude-modulate band-passed stochastic signals to produce an impulse response.
            try:
                responses = noise_shaping(audio_sample_rate,
                                          frequencies, envelopes)
            except Exception as exc:
                raise RuntimeError(f'Failed to generate responses for simulation #{src_idx+1}.') from exc

            # Write results back to JSON.
            for rcv_idx in range(num_rcvs):
                # Note that the first index of "responses" is for the single source position.
                result_container['results'][src_idx]['responses'][rcv_idx]['receiverResults'] = responses[0, rcv_idx].tolist()

            # EDCs = schroeder_curves(audio_sample_rate, frequencies, MoDART_echograms)
            # EDCs = np.clip(EDCs, 1e-20, None)
            # EDCs = 10 * np.log10(EDCs)
            
            # time_axis = np.arange(0, response_duration, 1 / echogram_sample_rate)

            # for rcv_idx in range(num_rcvs):
            #     for freq_idx, freq in enumerate(frequencies):
            #         result_container['results'][src_idx]['responses'][rcv_idx]['receiverResults'].append(
            #             {
            #                 'data': EDCs[src_idx, rcv_idx, freq_idx].tolist(),
            #                 't': time_axis.tolist(),
            #                 'frequency': freq,
            #                 'type': 'edc',
            #             }
            #         )

            result_container['results'][src_idx]['percentage'] = 100
            # Save the updated JSON.
            with open(self.input_json_path, 'w') as json_output:
                json_output.write(json.dumps(result_container, indent=4))

        print('MoDART simulation completed successfully!')


def test_noise_shaping_flatness():
    from matplotlib import pyplot as plt

    for order in range(1, 12, 2):
        resp = np.zeros(4097)
        for i in range(100):
            responses = noise_shaping(44100,
                                      np.array([2.5e2, 5e2, 1e3, 2e3, 4e3, 8e3]),
                                      np.ones((1, 1, 6, 88200)),
                                      order)
            response = responses.squeeze()

            transf = np.fft.rfft(response, n=2**13)
            resp += np.abs(transf)
        resp /= 100

        plt.plot(resp, label=order)
    
    plt.xscale('log')
    plt.yscale('log')
    plt.legend()
    plt.show()

  
# if __name__ == "__main__":
#     test_noise_shaping_flatness()
